"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

export type Language = "en" | "ja" | "ru";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.dashboard.description": "Overview and analytics",
    "nav.search": "Search",
    "nav.search.description": "Find businesses",
    "nav.history": "History",
    "nav.history.description": "View search history",
    history: "History",
    "nav.manageGroups": "Manage Groups",
    "nav.manageGroups.description": "Manage contact groups",
    "nav.settings": "Settings",
    "nav.settings.description": "Customize your experience",
    "nav.testSearch": "Test Search",
    "nav.testSearch.description": "Test search functionality",
    "nav.singleWebsite": "Single Website",
    "nav.singleWebsite.description": "Search single website",
    "nav.testMessage": "Test Message",
    "nav.testMessage.description": "Test single message sending",
    "nav.adminPanel": "Admin Panel",
    "nav.adminPanel.description": "Admin dashboard",
    "nav.moreTools": "More Tools",
    "nav.moreTools.description": "Additional features",
    "nav.archiveSearch": "Archive Search",
    "nav.archiveSearch.description": "Search archived data",
    "nav.businessOutreach": "Business Platform",
    "nav.captchaStatus": "CAPTCHA Status",

    // Settings page
    "settings.title": "Settings",
    "settings.description":
      "Customize your Auto Reach Pro experience with personalized settings and preferences.",
    "settings.appearance": "Appearance",
    "settings.appearance.description":
      "Choose your preferred color scheme and theme.",
    "settings.notifications": "Notifications",
    "settings.notifications.description":
      "Control which notifications you receive and how.",
    "settings.designSystem": "Design System",
    "settings.designSystem.description":
      "Explore the available UI components and their variants.",
    "settings.colorPalette": "Color Palette",
    "settings.colorPalette.description":
      "The accessible color system used throughout the interface.",
    "settings.theme": "Theme",
    "settings.current": "Current",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.system": "System",
    "settings.light.description": "Clean and bright interface",
    "settings.dark.description": "Easy on the eyes",
    "settings.system.description": "Follows your OS preference",
    "settings.emailNotifications": "Email Notifications",
    "settings.pushNotifications": "Push Notifications",
    "settings.smsNotifications": "SMS Notifications",
    "settings.notificationDescription":
      "Receive {type} notifications for important updates",
    "settings.buttonVariants": "Button Variants",
    "settings.buttonSizes": "Button Sizes",
    "settings.buttonStates": "Button States",
    "settings.cardVariants": "Card Variants",
    "settings.tooltipPositions": "Tooltip Positions",
    "settings.resetDefaults": "Reset to Defaults",
    "settings.saveChanges": "Save Changes",
    "settings.primary": "Primary",
    "settings.secondary": "Secondary",
    "settings.outline": "Outline",
    "settings.ghost": "Ghost",
    "settings.success": "Success",
    "settings.warning": "Warning",
    "settings.error": "Error",
    "settings.defaultCard": "Default Card",
    "settings.elevatedCard": "Elevated Card",
    "settings.outlinedCard": "Outlined Card",
    "settings.interactiveCard": "Interactive Card",
    "settings.defaultCard.description": "Standard card with default styling",
    "settings.elevatedCard.description":
      "Card with enhanced shadows and hover effects",
    "settings.outlinedCard.description": "Card with subtle border styling",
    "settings.interactiveCard.description": "Clickable card with hover states",
    "settings.topTooltip": "This tooltip appears above",
    "settings.bottomTooltip": "This tooltip appears below",
    "settings.leftTooltip": "This tooltip appears to the left",
    "settings.rightTooltip": "This tooltip appears to the right",
    "settings.language": "Language",
    "settings.language.description":
      "Choose your preferred language for the interface.",
    "settings.english": "English",
    "settings.japanese": "Japanese",
    "settings.russian": "Russian",
    "settings.english.description": "Default language",
    "settings.japanese.description": "日本語インターフェース",
    "settings.russian.description": "Русский интерфейс",

    // Common UI
    "ui.signOut": "Sign out",
    "ui.user": "User",
    "ui.loading": "Loading...",
    "ui.error": "Error",
    "ui.success": "Success",
    "ui.warning": "Warning",
    "ui.info": "Information",
    "ui.confirm": "Confirm",
    "ui.cancel": "Cancel",
    "ui.save": "Save",
    "ui.delete": "Delete",
    "ui.edit": "Edit",
    "ui.add": "Add",
    "ui.search": "Search",
    "ui.filter": "Filter",
    "ui.sort": "Sort",
    "ui.refresh": "Refresh",
    "ui.close": "Close",
    "ui.open": "Open",
    "ui.next": "Next",
    "ui.previous": "Previous",
    "ui.submit": "Submit",
    "ui.reset": "Reset",
    "ui.selectAll": "Select All",
    "ui.deselectAll": "Deselect All",
    "ui.selected": "selected",
    "ui.clear": "Clear",

    // Page titles and headers
    "pages.searchHistory.title": "Search History",
    "pages.searchHistory.description": "View and manage your previous searches",
    "pages.searchHistory.loading": "Loading search history...",
    "pages.searchHistory.noHistory": "No search history",
    "pages.searchHistory.noResults": "No results found",
    "pages.searchHistory.startFirstSearch":
      "Start your first search to see history here",
    "pages.searchHistory.tryAdjusting": "Try adjusting your search terms",

    // Search history specific
    "searchHistory.search": "Search by category, keywords, or areas...",
    "searchHistory.searchType": "Type",
    "searchHistory.found": "Found",
    "searchHistory.businesses": "businesses",
    "searchHistory.duration": "Duration",
    "searchHistory.date": "Date",
    "searchHistory.keywords": "Keywords",
    "searchHistory.areas": "Areas",
    "searchHistory.results": "Results",
    "searchHistory.totalResults": "total results",
    "searchHistory.noResultsFound": "No results found.",
    "searchHistory.cleanupExpired": "Cleanup Expired",
    "searchHistory.cleaning": "Cleaning...",

    // Pagination
    "pagination.previous": "Previous",
    "pagination.next": "Next",
    "pagination.page": "Page",
    "pagination.of": "of",
    "pagination.showing": "Showing",
    "pagination.to": "to",
    "pagination.results": "results",
    "pagination.loadMore": "Load More",

    // CAPTCHA Status page
    "pages.captchaStatus.title": "CAPTCHA Service Status",
    "pages.captchaStatus.troubleshooting": "Troubleshooting CAPTCHA Issues",
    "pages.captchaStatus.errorZeroBalance": "❌ ERROR_ZERO_BALANCE",
    "pages.captchaStatus.errorZeroBalanceDesc":
      "Your CAPTCHA solving service account has insufficient funds. Add money to your account to continue using automated CAPTCHA solving.",
    "pages.captchaStatus.noServiceConfigured":
      "⚠️ No CAPTCHA Service Configured",
    "pages.captchaStatus.noServiceConfiguredDesc":
      "No CAPTCHA solving service is configured. Add your API keys to the environment variables.",
    "pages.captchaStatus.alternativeSolutions": "💡 Alternative Solutions",
    "pages.captchaStatus.alternativeSolutionsDesc":
      "Use multiple CAPTCHA services for redundancy",
    "pages.captchaStatus.manualSolving":
      "Implement manual CAPTCHA solving for critical forms",
    "pages.captchaStatus.captchaFree":
      "Use CAPTCHA-free form submission when possible",
    "pages.captchaStatus.monitorBalances": "Monitor service balances regularly",
    "pages.captchaStatus.quickSetupGuide": "Quick Setup Guide",
    "pages.captchaStatus.twoCaptcha": "1. 2captcha.com (Recommended)",
    "pages.captchaStatus.visit2captcha": "Visit",
    "pages.captchaStatus.createAccount": "Create an account",
    "pages.captchaStatus.addFunds": "Add funds (minimum $3-5)",
    "pages.captchaStatus.getApiKey": "Get your API key",
    "pages.captchaStatus.addToEnv": "Add to .env.local:",
    "pages.captchaStatus.antiCaptcha": "2. Anti-Captcha (Alternative)",

    // Group management
    "groups.addToGroup": "Add to Group",
    "groups.manageGroups": "Manage Groups",
    "groups.loadingGroups": "Loading groups...",
    "groups.noGroupsFound": "No groups found. Create a group first.",
    "groups.createFirstGroup": "Create Your First Group",
    "groups.addingToGroup": "Adding to group",
    "groups.successfullyAdded": "successfully!",
    "groups.addSelectedToGroup": "Add Selected to Group",
    "groups.selectGroupToAdd": "Select a group to add",
    "groups.selectedBusinesses": "selected business(es)",
    "groups.to": "to:",
    "groups.pleaseSignIn": "Please sign in to manage groups.",
    "groups.groupManagement": "Group Management",
    "groups.visitDedicatedPage":
      "To manage your contact groups, please visit the dedicated group management page.",
    "groups.goToGroupManagement": "Go to Group Management",
    "groups.createGroup": "Create Group",
    "groups.deleteGroup": "Delete Group",
    "groups.sendMessage": "Send Message",
    "groups.loading": "Loading...",
    "groups.loadingSession": "Loading session...",
    "groups.loadingMessageForm": "Loading...",
    "groups.sending": "Sending...",
    "groups.messageDeleted": "Message deleted successfully!",
    "groups.messageDeleteError": "Failed to delete message",
    "groups.groupCreated": "Group created successfully!",
    "groups.groupCreateError": "Failed to create group",
    "groups.groupDeleted": "Group deleted successfully!",
    "groups.groupDeleteError": "Failed to delete group",
    "groups.contactRemoved": "Contact removed successfully!",
    "groups.contactRemoveError": "Failed to remove contact",
    "groups.notesUpdated": "Notes updated successfully!",
    "groups.notesUpdateError": "Failed to update notes",
    "groups.messagingEnabled": "Messaging enabled",
    "groups.messagingDisabled": "Messaging disabled",
    "groups.backgroundSend": "Background Send",
    "groups.manualSend": "Manual Send",
    "groups.retry": "Retry",
    "groups.manual": "Manual",
    "groups.notes": "Notes",
    "groups.addNotes": "Add notes",
    "groups.editNotes": "Edit notes",
    "groups.noNotes": "No notes added yet",
    "groups.save": "Save",
    "groups.cancel": "Cancel",
    "groups.edit": "Edit",
    "groups.remove": "Remove",
    "groups.close": "Close",
    "groups.contacts": "contacts",
    "groups.created": "Created",
    "groups.noContacts": "No contacts yet",
    "groups.noContactsFiltered": "No contacts found",
    "groups.addContactsFromSearch":
      "Add contacts to this group from your search results.",
    "groups.noContactsWithStatus": "No contacts with {status} status found.",
    "groups.filterByStatus": "Filter by Status:",
    "groups.all": "All",
    "groups.success": "Success",
    "groups.failed": "Failed",
    "groups.pending": "Pending",
    "groups.messageContext": "Message Context for",
    "groups.customizeMessage": "Customize Message",
    "groups.subject": "Subject",
    "groups.message": "Message",
    "groups.customSubject": "Custom subject (optional)",
    "groups.customMessage": "Custom message (optional)",
    "groups.backgroundMessageStatus": "Background Message Status",
    "groups.individualBackgroundSend":
      "Send message to this contact using background automation",
    "groups.retryOpenForm": "Retry - Open contact form in new window",
    "groups.markAsManuallySent": "Mark as Manually Sent",
    "groups.removeFromGroup": "Remove from group",
    "groups.lastSent": "Last Sent",
    "groups.lastFailed": "Last Failed",
    "groups.retryFailedContacts": "Retry Failed Contacts",
    "groups.someContactsFailed":
      "Some contacts failed to receive messages. You can retry them individually:",
    "groups.retryThisContact": "Retry this contact - Open form in new window",
    "groups.savedMessages": "Saved Messages for",
    "groups.noSavedMessages":
      "No saved messages yet. Save a message to see it here.",
    "groups.use": "Use",
    "groups.messageRecipients": "Message Recipients",
    "groups.onlyEnabledContacts":
      "Only contacts with messaging enabled will receive this message",
    "groups.backgroundSendTitle":
      "Send messages in background using browser automation",
    "groups.manualSendTitle": "Send messages immediately",
    "groups.autoGenerateSubject":
      "Leave empty to auto-generate subject from business names",
    "groups.enterMessageSubject": "Enter message subject",
    "groups.enterMessageBody": "Enter your message",
    "groups.aiSuggestions": "Get AI suggestions to improve your message",
    "groups.aiImprovedMessage": "AI has improved your message!",
    "groups.aiCorrectionFailed": "AI correction failed",
    "groups.clickAiButton":
      "Click the AI button to get suggestions for improving your message",
    "groups.groupInformation": "Group Information",
    "groups.of": "of",
    "groups.enabled": "enabled",
    "groups.confirmDeleteGroup":
      "Are you sure you want to delete this group? This action cannot be undone.",
    "groups.confirmRemoveContact":
      "Are you sure you want to remove this contact from the group?",
    "groups.testSendMessage": "Test Send Message",
    "groups.groupDetailsClosed": "Group details closed",
    "groups.messagingToggleError": "Failed to update messaging toggle",
    "groups.messagingEnabledFor": "Messaging enabled for",
    "groups.messagingDisabledFor": "Messaging disabled for",
    "groups.queuedMessageFor":
      "Queued message for {businessName} in background processing.",
    "groups.failedToQueueMessage": "Failed to queue message for {businessName}",
    "groups.queuedMessages":
      "Queued {count} messages for background processing. Check the progress panel below.",
    "groups.noContactsEnabled":
      "No contacts have messaging enabled. Please enable messaging for at least one contact.",
    "groups.messagesSentSuccessfully":
      "Messages sent successfully to all {count} contacts!",
    "groups.messagesFailed": "{count} messages failed: {businessNames}",
    "groups.failedToSendTo": "Failed to send to {businessName}: {error}",
    "groups.markedAsManuallySent": "Marked as manually sent for {businessName}",
    "groups.failedToUpdateStatus": "Failed to update status",
    "groups.formOpenedAndFilled":
      "Form opened and filled for {businessName}. Please review and submit manually.",
    "groups.formOpened":
      "Form opened for {businessName}. Please fill it out manually.",
    "groups.noContactPage":
      "No contact page or website available for this business",
    "groups.popupBlocked": "Popup blocked! Please allow popups for this site.",
    "groups.businessMessageContextSaved": "Business message context saved!",
    "groups.failedToSaveContext": "Failed to save business message context",
    "groups.description": "Description",
    "groups.color": "Color",
    "groups.enterGroupName": "Enter group name",
    "groups.enterGroupDescription": "Enter group description (optional)",

    // Map page
    "map.title": "Interactive Map",
    "map.markers": "markers",
    "map.instructions": "How to use:",
    "map.clickInstruction":
      "Click anywhere on the map to add a marker and get coordinates",
    "map.selectInstruction":
      "Select markers from the list below to view details",
    "map.copyInstruction": "Click coordinate values to copy them to clipboard",
    "map.selectedLocation": "Selected Location",
    "map.latitude": "Latitude:",
    "map.longitude": "Longitude:",
    "map.timestamp": "Timestamp:",
    "map.clickToCopy": "Click to copy",
    "map.copyCoordinates": "Copy Coordinates",
    "map.coordinateHistory": "Coordinate History",
    "map.noCoordinates": "No coordinates yet. Click on the map to add some!",
    "map.deleteMarker": "Delete marker",
    "map.clearAll": "Clear All",
    "map.geographicalSearch": "Geographical Search",
    "map.searchRadius": "Search Radius",
    "map.searchNearby": "Search Nearby",
    "map.searching": "Searching...",
    "map.clear": "Clear",
    "map.selectLocationFirst": "Please select a location on the map first",
    "map.searchError": "An error occurred during search",
    "map.searchResults": "Search Results",
    "map.viewOnMap": "View on Map",
    "map.quickActions": "Quick Actions",
    "map.defaultLocation": "Default Location",
    "map.searchFromDefault": "🔍 Search from Default Location",
    "map.resetToDefault": "🏠 Reset to Default View",
    "map.quickSearch":
      "Use 'Search from Default Location' to quickly find businesses in central Tokyo",
    "map.contactClick":
      "Click contact buttons to copy phone numbers, emails, or visit websites",
    "map.locationSearch": "Location Search",
    "map.searchPlaceholder": "Enter location (e.g., Shibuya, Ginza, Asakusa)",
    "map.enterLocation": "Please enter a location",
    "map.locationNotFound": "Location not found. Try a different search term.",
    "map.locationSearchInstruction":
      "Use the Location Search to find specific places in Tokyo",

    // Settings - Company & Product Management
    "settings.company": "Company Information",
    "settings.company.description":
      "Manage your company details and description",
    "settings.companyDescription": "Company Description",
    "settings.companyDescription.placeholder":
      "Describe your company, services, and what makes you unique...",
    "settings.companyDescriptionRequired": "Company description is required",
    "settings.saveCompany": "Save Company Information",
    "settings.savingCompany": "Saving...",
    "settings.companySaved": "Company information saved successfully!",
    "settings.companySaveError": "Failed to save company information",
    "settings.companyLoadError": "Failed to load company information",

    "settings.products": "Product Management",
    "settings.products.description": "Create and manage your product catalog",
    "settings.addProduct": "Add New Product",
    "settings.productDescription": "Product Description",
    "settings.productDescription.placeholder":
      "Detailed product description...",
    "settings.productDescriptionRequired": "Product description is required",
    "settings.saveProduct": "Add Product",
    "settings.savingProduct": "Saving...",
    "settings.productSaved": "Product added successfully!",
    "settings.productSaveError": "Failed to add product",
    "settings.yourProducts": "Your Products",
    "settings.editProduct": "Edit",
    "settings.deleteProduct": "Delete",
    "settings.productUpdated": "Product updated successfully!",
    "settings.productUpdateError": "Failed to update product",
    "settings.productDeleted": "Product deleted successfully!",
    "settings.productDeleteError": "Failed to delete product",
    "settings.productsLoadError": "Failed to load products",
    "settings.noProducts": "No products found",
    "settings.noProducts.description":
      "Get started by adding your first product",
    "settings.created": "Created",
    "settings.loading": "Loading...",
    "settings.charactersRemaining": "characters remaining",
    "settings.authRequired": "Please sign in to access settings",
    "settings.authError": "Authentication error. Please sign in again.",
    "settings.databaseSetupRequired":
      "Database not set up. Please run the setup script in Supabase SQL Editor.",

    // Form and actions
    "actions.selectAll": "Select All",
    "actions.clearSelection": "Clear Selection",
    "actions.selected": "selected",
    "actions.of": "of",
    "actions.previous": "Previous",
    "actions.next": "Next",
    "actions.page": "Page",
    "actions.cancel": "Cancel",
    "actions.website": "Website",
    "actions.enterWebsite": "Please enter a website URL",
    "actions.search": "Search",
    "actions.searching": "Searching...",
    "actions.copyFormData": "Copy Form Data for Manual Submission",
    "actions.manualSubmissionNote":
      "The system will attempt to find and submit to contact forms automatically. You can also copy the form data and submit it manually to any contact form you find.",

    // Authentication
    "auth.welcomeBack": "Welcome back",
    "auth.signInToAccount": "Sign in to your AutoReachPro account",
    "auth.emailAddress": "Email address",
    "auth.password": "Password",
    "auth.signIn": "Sign In",
    "auth.invalidCredentials": "Invalid email or password",
    "auth.errorOccurred": "An error occurred. Please try again.",
    "auth.loading": "Loading...",

    // Business and contact
    "business.name": "Name",
    "business.email": "Email",
    "business.phone": "Phone",
    "business.company": "Company",
    "business.subject": "Subject",
    "business.message": "Message",
    "business.address": "Address",
    "business.website": "Website",
    "business.contact": "Contact",
    "business.contactPage": "Contact Page",
    "business.rating": "Rating",
    "business.reviews": "Reviews",
    "business.category": "Category",
    "business.region": "Region",
    "business.area": "Area",
    "business.station": "Station",
    "business.status": "Status",
    "business.lastSearched": "Last Searched",

    // Additional auth and common text
    "auth.dontHaveAccount": "Don't have an account?",
    "auth.createOneNow": "Create one now",
    "auth.agreeToTerms": "By signing in, you agree to our",
    "auth.termsOfService": "Terms of Service",
    "auth.and": "and",
    "auth.privacyPolicy": "Privacy Policy",
    "auth.enterEmail": "Enter your email",
    "auth.enterPassword": "Enter your password",
    "auth.signingIn": "Signing in...",

    // Dashboard
    "dashboard.welcomeBack": "Welcome back",
    "dashboard.welcomeMessage":
      "Here's what's happening with your business outreach campaigns",
    "dashboard.totalSearches": "Total Searches",
    "dashboard.businessesFound": "Businesses Found",
    "dashboard.contactForms": "Contact Forms",
    "dashboard.successRate": "Success Rate",
    "dashboard.fromLastMonth": "from last month",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.startSearch": "Start Search",
    "dashboard.startSearchDesc": "Find new businesses",
    "dashboard.manageGroups": "Manage Groups",
    "dashboard.manageGroupsDesc": "Organize contacts",
    "dashboard.testMessage": "Test Message",
    "dashboard.testMessageDesc": "Send test emails",
    "dashboard.viewHistory": "View History",
    "dashboard.viewHistoryDesc": "Past searches",
    "dashboard.recentSearches": "Recent Searches",
    "dashboard.viewAll": "View all",
    "dashboard.noRecentSearches": "No recent searches",
    "dashboard.startFirstSearch": "Start your first search",
    "dashboard.found": "found",
    "dashboard.noRegionsSpecified": "No regions specified",
    "dashboard.systemAction": "System action",

    // Search and Group Management
    "search.addToGroup": "Add to Group",
    "search.addToGroupTitle": "Add to group",
    "search.addingToGroup": "Adding to group",
    "search.successfullyAdded": "successfully!",
    "search.loadingGroups": "Loading groups...",
    "search.noGroupsFound": "No groups found. Create a group first.",
    "search.createFirstGroup": "Create Your First Group",
    "search.manageGroups": "Manage Groups",
    "search.visitDedicatedPage":
      "To manage your contact groups, please visit the dedicated group management page.",
    "search.goToGroupManagement": "Go to Group Management",
    "search.selectGroupToAdd": "Select a group to add",
    "search.selectedBusinesses": "selected business(es)",
    "search.to": "to:",
    "search.pleaseSignIn": "Please sign in to manage groups.",
    "search.groupManagement": "Group Management",

    // Search functionality
    "search.searchBusinesses": "Search Businesses",
    "search.searchDescription":
      "Find businesses by category, region, or keywords",
    "search.selectCategory": "Select Category",
    "search.selectRegion": "Select Region",
    "search.enterKeywords": "Enter Keywords",
    "search.searchButton": "Search",
    "search.searching": "Searching...",
    "search.noResults": "No results found",
    "search.tryAdjusting": "Try adjusting your search criteria",
    "search.businessesFound": "businesses found",
    "search.loadingResults": "Loading results...",
    "search.contactForms": "Contact Forms",
    "search.contactFormsFound": "contact forms found",
    "search.contactForm": "Contact Form",
    "search.quickSend": "Quick Send",
    "search.viewDetails": "View Details",
    "search.copyFormData": "Copy Form Data",
    "search.formDataCopied": "Form data copied to clipboard",

    // Time formatting
    "time.justNow": "Just now",
    "time.minuteAgo": "minute ago",
    "time.minutesAgo": "minutes ago",
    "time.hourAgo": "hour ago",
    "time.hoursAgo": "hours ago",
    "time.yesterday": "Yesterday",
    "time.daysAgo": "days ago",
    "time.weeksAgo": "weeks ago",
    "time.never": "Never",

    // Admin Dashboard
    "admin.dashboard": "Admin Dashboard",
    "admin.users": "Users",
    "admin.actions": "Actions",
    "admin.addUser": "Add User",
    "admin.editUser": "Edit User",
    "admin.deleteUser": "Delete User",
    "admin.userEmail": "Email",
    "admin.userName": "Name",
    "admin.userPassword": "Password",
    "admin.userRole": "Role",
    "admin.userStatus": "Status",
    "admin.userCreated": "Created",
    "admin.userUpdated": "Updated",
    "admin.active": "Active",
    "admin.inactive": "Inactive",
    "admin.admin": "Admin",
    "admin.user": "User",
    "admin.searchUsers": "Search users...",
    "admin.noUsers": "No users found",
    "admin.loadingUsers": "Loading users...",
    "admin.confirmDeleteUser": "Are you sure you want to delete this user?",
    "admin.deleteSuccess": "User deleted successfully",
    "admin.deleteError": "Error deleting user",
    "admin.addSuccess": "User added successfully",
    "admin.addError": "Error adding user",
    "admin.updateSuccess": "User updated successfully",
    "admin.updateError": "Error updating user",
    "admin.userActions": "User Actions",
    "admin.actionType": "Action Type",
    "admin.actionDetails": "Details",
    "admin.actionDate": "Date",
    "admin.actionIP": "IP Address",
    "admin.actionUserAgent": "User Agent",
    "admin.noActions": "No actions found",
    "admin.loadingActions": "Loading actions...",
    "admin.pagination": "Page",
    "admin.of": "of",
    "admin.previous": "Previous",
    "admin.next": "Next",
    "admin.itemsPerPage": "items per page",
    "admin.manageUsersAndMonitor": "Manage users and monitor system activity",
  },
  ja: {
    // Navigation
    "nav.dashboard": "ダッシュボード",
    "nav.dashboard.description": "概要と分析を確認",
    "nav.search": "検索",
    "nav.search.description": "ビジネスを検索",
    "nav.history": "履歴",
    "nav.history.description": "検索履歴を見る",
    history: "検索履歴",
    "nav.manageGroups": "グループ管理",
    "nav.manageGroups.description": "連絡先グループを管理",
    "nav.settings": "設定",
    "nav.settings.description": "好みに合わせてカスタマイズ",
    "nav.testSearch": "テスト検索",
    "nav.testSearch.description": "検索機能をテスト",
    "nav.singleWebsite": "単一ウェブサイト",
    "nav.singleWebsite.description": "特定のウェブサイトを検索",
    "nav.testMessage": "テストメッセージ",
    "nav.testMessage.description": "メッセージ送信をテスト",
    "nav.adminPanel": "管理者パネル",
    "nav.adminPanel.description": "管理者用ダッシュボード",
    "nav.moreTools": "その他のツール",
    "nav.moreTools.description": "追加の便利な機能",
    "nav.archiveSearch": "アーカイブ検索",
    "nav.archiveSearch.description": "アーカイブされたデータを検索",
    "nav.businessOutreach": "オートリーチ・プロ",
    "nav.captchaStatus": "CAPTCHA状況",

    // Settings page
    "settings.title": "設定",
    "settings.description":
      "Auto Reach Proをあなた好みにカスタマイズしましょう。言語、テーマ、通知などの設定が可能です。",
    "settings.appearance": "外観",
    "settings.appearance.description":
      "お好みの色合いとテーマをお選びください。",
    "settings.notifications": "通知",
    "settings.notifications.description":
      "受け取りたい通知とその方法を設定できます。",
    "settings.designSystem": "デザインシステム",
    "settings.designSystem.description":
      "利用できるUIコンポーネントとその種類をご覧ください。",
    "settings.colorPalette": "カラーパレット",
    "settings.colorPalette.description":
      "インターフェース全体で使用されている使いやすい配色システムです。",
    "settings.theme": "テーマ",
    "settings.current": "現在の設定",
    "settings.light": "ライト",
    "settings.dark": "ダーク",
    "settings.system": "システム",
    "settings.light.description": "明るく清潔なインターフェース",
    "settings.dark.description": "目に優しい暗めの配色",
    "settings.system.description": "お使いのOSの設定に合わせる",
    "settings.emailNotifications": "メール通知",
    "settings.pushNotifications": "プッシュ通知",
    "settings.smsNotifications": "SMS通知",
    "settings.notificationDescription": "重要な更新の{type}通知を受信",
    "settings.buttonVariants": "ボタンバリエーション",
    "settings.buttonSizes": "ボタンサイズ",
    "settings.buttonStates": "ボタン状態",
    "settings.cardVariants": "カードバリエーション",
    "settings.tooltipPositions": "ツールチップ位置",
    "settings.resetDefaults": "デフォルトにリセット",
    "settings.saveChanges": "変更を保存",
    "settings.primary": "プライマリ",
    "settings.secondary": "セカンダリ",
    "settings.outline": "アウトライン",
    "settings.ghost": "ゴースト",
    "settings.success": "成功",
    "settings.warning": "警告",
    "settings.error": "エラー",
    "settings.defaultCard": "デフォルトカード",
    "settings.elevatedCard": "エレベーテッドカード",
    "settings.outlinedCard": "アウトラインカード",
    "settings.interactiveCard": "インタラクティブカード",
    "settings.defaultCard.description": "標準的なスタイリングのカード",
    "settings.elevatedCard.description":
      "エンハンスされたシャドウとホバーエフェクトのカード",
    "settings.outlinedCard.description": "繊細なボーダースタイリングのカード",
    "settings.interactiveCard.description": "ホバー状態のクリック可能なカード",
    "settings.topTooltip": "このツールチップは上に表示されます",
    "settings.bottomTooltip": "このツールチップは下に表示されます",
    "settings.leftTooltip": "このツールチップは左に表示されます",
    "settings.rightTooltip": "このツールチップは右に表示されます",
    "settings.language": "言語",
    "settings.language.description":
      "インターフェースの言語を選択してください。",
    "settings.english": "英語",
    "settings.japanese": "日本語",
    "settings.russian": "ロシア語",
    "settings.english.description": "デフォルト言語",
    "settings.japanese.description": "日本語インターフェース",
    "settings.russian.description": "ロシア語インターフェース",

    // Common UI
    "ui.signOut": "サインアウト",
    "ui.user": "ユーザー",
    "ui.loading": "読み込み中...",
    "ui.error": "エラー",
    "ui.success": "完了",
    "ui.warning": "注意",
    "ui.info": "情報",
    "ui.confirm": "確認",
    "ui.cancel": "キャンセル",
    "ui.save": "保存",
    "ui.delete": "削除",
    "ui.edit": "編集",
    "ui.add": "追加",
    "ui.search": "検索",
    "ui.filter": "絞り込み",
    "ui.sort": "並び替え",
    "ui.refresh": "再読み込み",
    "ui.close": "閉じる",
    "ui.open": "開く",
    "ui.next": "次へ",
    "ui.previous": "前へ",
    "ui.submit": "送信する",
    "ui.reset": "リセット",
    "ui.selectAll": "すべて選択",
    "ui.deselectAll": "選択を解除",
    "ui.selected": "選択済み",
    "ui.clear": "クリア",

    // Page titles and headers
    "pages.searchHistory.title": "検索履歴",
    "pages.searchHistory.description": "以前の検索を表示・管理",
    "pages.searchHistory.loading": "検索履歴を読み込み中...",
    "pages.searchHistory.noHistory": "検索履歴がありません",
    "pages.searchHistory.noResults": "結果が見つかりません",
    "pages.searchHistory.startFirstSearch": "最初の検索を開始して履歴を表示",
    "pages.searchHistory.tryAdjusting": "検索語を調整してみてください",

    // Search history specific
    "searchHistory.search": "カテゴリ、キーワード、エリアで検索...",
    "searchHistory.searchType": "タイプ",
    "searchHistory.found": "見つかった",
    "searchHistory.businesses": "ビジネス",
    "searchHistory.duration": "期間",
    "searchHistory.date": "日付",
    "searchHistory.keywords": "キーワード",
    "searchHistory.areas": "エリア",
    "searchHistory.results": "結果",
    "searchHistory.totalResults": "総結果",
    "searchHistory.noResultsFound": "結果が見つかりません。",
    "searchHistory.cleanupExpired": "期限切れをクリーンアップ",
    "searchHistory.cleaning": "クリーンアップ中...",

    // Pagination
    "pagination.previous": "前へ",
    "pagination.next": "次へ",
    "pagination.page": "ページ",
    "pagination.of": "の",
    "pagination.showing": "表示中",
    "pagination.to": "から",
    "pagination.results": "件",
    "pagination.loadMore": "さらに読み込む",

    // CAPTCHA Status page
    "pages.captchaStatus.title": "CAPTCHAサービスステータス",
    "pages.captchaStatus.troubleshooting":
      "CAPTCHA問題のトラブルシューティング",
    "pages.captchaStatus.errorZeroBalance": "❌ ERROR_ZERO_BALANCE",
    "pages.captchaStatus.errorZeroBalanceDesc":
      "CAPTCHA解決サービスアカウントの残高が不足しています。自動CAPTCHA解決を続行するには、アカウントに資金を追加してください。",
    "pages.captchaStatus.noServiceConfigured":
      "⚠️ CAPTCHAサービスが設定されていません",
    "pages.captchaStatus.noServiceConfiguredDesc":
      "CAPTCHA解決サービスが設定されていません。環境変数にAPIキーを追加してください。",
    "pages.captchaStatus.alternativeSolutions": "💡 代替ソリューション",
    "pages.captchaStatus.alternativeSolutionsDesc":
      "冗長性のために複数のCAPTCHAサービスを使用",
    "pages.captchaStatus.manualSolving":
      "重要なフォームの手動CAPTCHA解決を実装",
    "pages.captchaStatus.captchaFree":
      "可能な場合はCAPTCHAフリーのフォーム送信を使用",
    "pages.captchaStatus.monitorBalances": "サービス残高を定期的に監視",
    "pages.captchaStatus.quickSetupGuide": "クイックセットアップガイド",
    "pages.captchaStatus.twoCaptcha": "1. 2captcha.com (推奨)",
    "pages.captchaStatus.visit2captcha": "訪問",
    "pages.captchaStatus.createAccount": "アカウントを作成",
    "pages.captchaStatus.addFunds": "資金を追加（最小$3-5）",
    "pages.captchaStatus.getApiKey": "APIキーを取得",
    "pages.captchaStatus.addToEnv": ".env.localに追加:",
    "pages.captchaStatus.antiCaptcha": "2. Anti-Captcha (代替)",

    // Group management
    "groups.addToGroup": "グループに追加",
    "groups.manageGroups": "グループ管理",
    "groups.loadingGroups": "グループを読み込み中...",
    "groups.noGroupsFound":
      "グループが見つかりません。最初にグループを作成してください。",
    "groups.createFirstGroup": "最初のグループを作成",
    "groups.addingToGroup": "グループに追加中",
    "groups.successfullyAdded": "成功しました！",
    "groups.addSelectedToGroup": "選択したものをグループに追加",
    "groups.selectGroupToAdd": "追加するグループを選択",
    "groups.selectedBusinesses": "選択されたビジネス",
    "groups.to": "に:",
    "groups.pleaseSignIn": "グループを管理するにはサインインしてください。",
    "groups.groupManagement": "グループ管理",
    "groups.visitDedicatedPage":
      "連絡先グループを管理するには、専用のグループ管理ページにアクセスしてください。",
    "groups.goToGroupManagement": "グループ管理に移動",
    "groups.createGroup": "グループ作成",
    "groups.deleteGroup": "グループ削除",
    "groups.sendMessage": "メッセージ送信",
    "groups.loading": "読み込み中...",
    "groups.loadingSession": "セッション読み込み中...",
    "groups.loadingMessageForm": "読み込み中...",
    "groups.sending": "送信中...",
    "groups.messageDeleted": "メッセージが正常に削除されました！",
    "groups.messageDeleteError": "メッセージの削除に失敗しました",
    "groups.groupCreated": "グループが正常に作成されました！",
    "groups.groupCreateError": "グループの作成に失敗しました",
    "groups.groupDeleted": "グループが正常に削除されました！",
    "groups.groupDeleteError": "グループの削除に失敗しました",
    "groups.contactRemoved": "連絡先が正常に削除されました！",
    "groups.contactRemoveError": "連絡先の削除に失敗しました",
    "groups.notesUpdated": "メモが正常に更新されました！",
    "groups.notesUpdateError": "メモの更新に失敗しました",
    "groups.messagingEnabled": "メッセージングが有効",
    "groups.messagingDisabled": "メッセージングが無効",
    "groups.backgroundSend": "バックグラウンド送信",
    "groups.manualSend": "手動送信",
    "groups.retry": "再試行",
    "groups.manual": "手動",
    "groups.notes": "メモ",
    "groups.addNotes": "メモを追加",
    "groups.editNotes": "メモを編集",
    "groups.noNotes": "まだメモが追加されていません",
    "groups.save": "保存",
    "groups.cancel": "キャンセル",
    "groups.edit": "編集",
    "groups.remove": "削除",
    "groups.close": "閉じる",
    "groups.contacts": "連絡先",
    "groups.created": "作成日",
    "groups.noContacts": "まだ連絡先がありません",
    "groups.noContactsFiltered": "連絡先が見つかりません",
    "groups.addContactsFromSearch":
      "検索結果からこのグループに連絡先を追加してください。",
    "groups.noContactsWithStatus":
      "{status}ステータスの連絡先が見つかりません。",
    "groups.filterByStatus": "ステータスでフィルター:",
    "groups.all": "すべて",
    "groups.success": "成功",
    "groups.failed": "失敗",
    "groups.pending": "保留中",
    "groups.messageContext": "メッセージコンテキスト",
    "groups.customizeMessage": "メッセージをカスタマイズ",
    "groups.subject": "件名",
    "groups.message": "メッセージ",
    "groups.customSubject": "カスタム件名（オプション）",
    "groups.customMessage": "カスタムメッセージ（オプション）",
    "groups.backgroundMessageStatus": "バックグラウンドメッセージステータス",
    "groups.individualBackgroundSend":
      "バックグラウンド自動化を使用してこの連絡先にメッセージを送信",
    "groups.retryOpenForm": "再試行 - 新しいウィンドウで連絡フォームを開く",
    "groups.markAsManuallySent": "手動送信済みとしてマーク",
    "groups.removeFromGroup": "グループから削除",
    "groups.lastSent": "最後に送信",
    "groups.lastFailed": "最後に失敗",
    "groups.retryFailedContacts": "失敗した連絡先を再試行",
    "groups.someContactsFailed":
      "一部の連絡先がメッセージを受信できませんでした。個別に再試行できます:",
    "groups.retryThisContact":
      "この連絡先を再試行 - 新しいウィンドウでフォームを開く",
    "groups.savedMessages": "保存されたメッセージ",
    "groups.noSavedMessages":
      "まだ保存されたメッセージがありません。メッセージを保存するとここに表示されます。",
    "groups.use": "使用",
    "groups.messageRecipients": "メッセージ受信者",
    "groups.onlyEnabledContacts":
      "メッセージングが有効な連絡先のみがこのメッセージを受信します",
    "groups.backgroundSendTitle":
      "バックグラウンドブラウザ自動化を使用してメッセージを送信",
    "groups.manualSendTitle": "メッセージを即座に送信",
    "groups.autoGenerateSubject":
      "空のままにすると、ビジネス名から件名が自動生成されます",
    "groups.enterMessageSubject": "メッセージの件名を入力",
    "groups.enterMessageBody": "メッセージを入力",
    "groups.aiSuggestions": "AIの提案でメッセージを改善",
    "groups.aiImprovedMessage": "AIがメッセージを改善しました！",
    "groups.aiCorrectionFailed": "AI修正に失敗しました",
    "groups.clickAiButton": "AIボタンをクリックしてメッセージ改善の提案を取得",
    "groups.groupInformation": "グループ情報",
    "groups.of": "の",
    "groups.enabled": "有効",
    "groups.confirmDeleteGroup":
      "このグループを削除してもよろしいですか？この操作は元に戻せません。",
    "groups.confirmRemoveContact":
      "この連絡先をグループから削除してもよろしいですか？",
    "groups.testSendMessage": "テストメッセージ送信",
    "groups.groupDetailsClosed": "グループ詳細が閉じられました",
    "groups.messagingToggleError": "メッセージングトグルの更新に失敗しました",
    "groups.messagingEnabledFor": "メッセージングが有効になりました",
    "groups.messagingDisabledFor": "メッセージングが無効になりました",
    "groups.queuedMessageFor":
      "{businessName}のメッセージがバックグラウンド処理でキューされました。",
    "groups.failedToQueueMessage":
      "{businessName}のメッセージのキューに失敗しました",
    "groups.queuedMessages":
      "{count}件のメッセージがバックグラウンド処理でキューされました。下の進行パネルを確認してください。",
    "groups.noContactsEnabled":
      "メッセージングが有効な連絡先がありません。少なくとも1つの連絡先でメッセージングを有効にしてください。",
    "groups.messagesSentSuccessfully":
      "{count}件の連絡先すべてにメッセージが正常に送信されました！",
    "groups.messagesFailed":
      "{count}件のメッセージが失敗しました: {businessNames}",
    "groups.failedToSendTo": "{businessName}への送信に失敗しました: {error}",
    "groups.markedAsManuallySent":
      "{businessName}を手動送信済みとしてマークしました",
    "groups.failedToUpdateStatus": "ステータスの更新に失敗しました",
    "groups.formOpenedAndFilled":
      "{businessName}のフォームが開かれ、入力されました。確認して手動で送信してください。",
    "groups.formOpened":
      "{businessName}のフォームが開かれました。手動で入力してください。",
    "groups.noContactPage":
      "このビジネスに利用可能な連絡ページやウェブサイトがありません",
    "groups.popupBlocked":
      "ポップアップがブロックされました！このサイトのポップアップを許可してください。",
    "groups.businessMessageContextSaved":
      "ビジネスメッセージコンテキストが保存されました！",
    "groups.failedToSaveContext":
      "ビジネスメッセージコンテキストの保存に失敗しました",
    "groups.description": "説明",
    "groups.color": "色",
    "groups.enterGroupName": "グループ名を入力",
    "groups.enterGroupDescription": "グループの説明を入力（オプション）",

    // Map page
    "map.title": "インタラクティブマップ",
    "map.markers": "マーカー",
    "map.instructions": "使い方:",
    "map.clickInstruction":
      "マップ上の任意の場所をクリックして、マーカーを追加し、座標を取得します",
    "map.selectInstruction": "下のリストからマーカーを選択して詳細を表示します",
    "map.copyInstruction": "座標値をクリックしてクリップボードにコピーします",
    "map.selectedLocation": "選択された場所",
    "map.latitude": "緯度:",
    "map.longitude": "経度:",
    "map.timestamp": "タイムスタンプ:",
    "map.clickToCopy": "クリックしてコピー",
    "map.copyCoordinates": "座標をコピー",
    "map.coordinateHistory": "座標履歴",
    "map.noCoordinates":
      "まだ座標がありません。マップをクリックして追加してください！",
    "map.deleteMarker": "マーカーを削除",
    "map.clearAll": "すべてクリア",
    "map.geographicalSearch": "地理検索",
    "map.searchRadius": "検索範囲",
    "map.searchNearby": "近くを検索",
    "map.searching": "検索中...",
    "map.clear": "クリア",
    "map.selectLocationFirst": "まず地図上で場所を選択してください",
    "map.searchError": "検索中にエラーが発生しました",
    "map.searchResults": "検索結果",
    "map.viewOnMap": "地図上で表示",
    "map.quickActions": "クイックアクション",
    "map.defaultLocation": "デフォルト位置",
    "map.searchFromDefault": "🔍 デフォルト位置から検索",
    "map.resetToDefault": "🏠 デフォルトビューにリセット",
    "map.quickSearch":
      "'デフォルト位置から検索'を使用して、中央東京のビジネスをすばやく検索",
    "map.contactClick":
      "連絡先ボタンをクリックして電話番号、メールをコピーするか、ウェブサイトにアクセス",
    "map.locationSearch": "場所検索",
    "map.searchPlaceholder": "場所を入力（例：渋谷、銀座、浅草）",
    "map.enterLocation": "場所を入力してください",
    "map.locationNotFound":
      "場所が見つかりません。別の検索語を試してください。",
    "map.locationSearchInstruction":
      "場所検索を使用して東京の特定の場所を見つける",

    // Settings - Company & Product Management
    "settings.company": "会社情報",
    "settings.company.description": "会社詳細と説明を管理",
    "settings.companyDescription": "会社説明",
    "settings.companyDescription.placeholder":
      "会社、サービス、独自性を説明...",
    "settings.companyDescriptionRequired": "会社説明が必要です",
    "settings.saveCompany": "会社情報を保存",
    "settings.savingCompany": "保存中...",
    "settings.companySaved": "会社情報が正常に保存されました！",
    "settings.companySaveError": "会社情報の保存に失敗しました",
    "settings.companyLoadError": "会社情報の読み込みに失敗しました",

    "settings.products": "製品管理",
    "settings.products.description": "製品カタログを作成・管理",
    "settings.addProduct": "新規製品を追加",
    "settings.productDescription": "製品説明",
    "settings.productDescription.placeholder": "詳細な製品説明...",
    "settings.productDescriptionRequired": "製品説明が必要です",
    "settings.saveProduct": "製品を追加",
    "settings.savingProduct": "保存中...",
    "settings.productSaved": "製品が正常に追加されました！",
    "settings.productSaveError": "製品の追加に失敗しました",
    "settings.yourProducts": "あなたの製品",
    "settings.editProduct": "編集",
    "settings.deleteProduct": "削除",
    "settings.productUpdated": "製品が正常に更新されました！",
    "settings.productUpdateError": "製品の更新に失敗しました",
    "settings.productDeleted": "製品が正常に削除されました！",
    "settings.productDeleteError": "製品の削除に失敗しました",
    "settings.productsLoadError": "製品の読み込みに失敗しました",
    "settings.noProducts": "製品が見つかりません",
    "settings.noProducts.description": "最初の製品を追加して開始",
    "settings.created": "作成日",
    "settings.loading": "読み込み中...",
    "settings.charactersRemaining": "文字残り",
    "settings.authRequired": "設定にアクセスするにはサインインしてください",
    "settings.authError": "認証エラー。再度サインインしてください。",
    "settings.databaseSetupRequired":
      "データベースが設定されていません。Supabase SQL Editorでセットアップスクリプトを実行してください。",

    // Form and actions
    "actions.selectAll": "すべて選択",
    "actions.clearSelection": "選択をクリア",
    "actions.selected": "選択済み",
    "actions.of": "の",
    "actions.previous": "前へ",
    "actions.next": "次へ",
    "actions.page": "ページ",
    "actions.cancel": "キャンセル",
    "actions.website": "ウェブサイト",
    "actions.enterWebsite": "ウェブサイトのURLを入力してください",
    "actions.search": "検索",
    "actions.searching": "検索中...",
    "actions.copyFormData": "手動送信用のフォームデータをコピー",
    "actions.manualSubmissionNote":
      "システムは自動的に連絡フォームを見つけて送信しようとします。フォームデータをコピーして、見つけた連絡フォームに手動で送信することもできます。",

    // Authentication
    "auth.welcomeBack": "おかえりなさい",
    "auth.signInToAccount": "AutoReachProアカウントにログイン",
    "auth.emailAddress": "メールアドレス",
    "auth.password": "パスワード",
    "auth.signIn": "ログイン",
    "auth.invalidCredentials":
      "メールアドレスまたはパスワードが正しくありません",
    "auth.errorOccurred": "エラーが発生しました。もう一度お試しください。",
    "auth.loading": "読み込み中...",

    // Business and contact
    "business.name": "会社名",
    "business.email": "メールアドレス",
    "business.phone": "電話番号",
    "business.company": "会社",
    "business.subject": "件名",
    "business.message": "メッセージ",
    "business.address": "住所",
    "business.website": "ウェブサイト",
    "business.contact": "お問い合わせ",
    "business.contactPage": "お問い合わせページ",
    "business.rating": "評価",
    "business.reviews": "口コミ",
    "business.category": "業種",
    "business.region": "地域",
    "business.area": "エリア",
    "business.station": "最寄り駅",
    "business.status": "状況",
    "business.lastSearched": "最終検索日",

    // Additional auth and common text
    "auth.dontHaveAccount": "アカウントをお持ちではありませんか？",
    "auth.createOneNow": "今すぐ作成する",
    "auth.agreeToTerms":
      "ログインすることで、以下の内容に同意したことになります",
    "auth.termsOfService": "利用規約",
    "auth.and": "および",
    "auth.privacyPolicy": "プライバシーポリシー",
    "auth.enterEmail": "メールアドレスを入力してください",
    "auth.enterPassword": "パスワードを入力してください",
    "auth.signingIn": "ログイン中...",

    // Dashboard
    "dashboard.welcomeBack": "おかえりなさい",
    "dashboard.welcomeMessage":
      "ビジネスアウトリーチキャンペーンの状況をご覧ください",
    "dashboard.totalSearches": "総検索数",
    "dashboard.businessesFound": "見つけたビジネス",
    "dashboard.contactForms": "連絡フォーム",
    "dashboard.successRate": "成功率",
    "dashboard.fromLastMonth": "先月比",
    "dashboard.quickActions": "クイックアクション",
    "dashboard.startSearch": "検索を開始",
    "dashboard.startSearchDesc": "新しいビジネスを探す",
    "dashboard.manageGroups": "グループ管理",
    "dashboard.manageGroupsDesc": "連絡先を整理する",
    "dashboard.testMessage": "テストメッセージ",
    "dashboard.testMessageDesc": "テストメールを送る",
    "dashboard.viewHistory": "履歴を見る",
    "dashboard.viewHistoryDesc": "過去の検索結果",
    "dashboard.recentSearches": "最近の検索",
    "dashboard.viewAll": "すべて見る",
    "dashboard.noRecentSearches": "最近の検索はありません",
    "dashboard.startFirstSearch": "最初の検索を始めましょう",
    "dashboard.found": "見つけた",
    "dashboard.noRegionsSpecified": "地域が指定されていません",
    "dashboard.systemAction": "システムアクション",

    // Search and Group Management
    "search.addToGroup": "グループに追加",
    "search.addToGroupTitle": "グループに追加",
    "search.addingToGroup": "グループに追加中",
    "search.successfullyAdded": "成功しました！",
    "search.loadingGroups": "グループを読み込み中...",
    "search.noGroupsFound":
      "グループが見つかりません。最初にグループを作成してください。",
    "search.createFirstGroup": "最初のグループを作成",
    "search.manageGroups": "グループ管理",
    "search.visitDedicatedPage":
      "連絡先グループを管理するには、専用のグループ管理ページにアクセスしてください。",
    "search.goToGroupManagement": "グループ管理に移動",
    "search.selectGroupToAdd": "追加するグループを選択",
    "search.selectedBusinesses": "選択されたビジネス",
    "search.to": "に:",
    "search.pleaseSignIn": "グループを管理するにはサインインしてください。",
    "search.groupManagement": "グループ管理",

    // Search functionality
    "search.searchBusinesses": "ビジネスを検索",
    "search.searchDescription":
      "カテゴリ、地域、またはキーワードでビジネスを見つける",
    "search.selectCategory": "カテゴリを選択",
    "search.selectRegion": "地域を選択",
    "search.enterKeywords": "キーワードを入力",
    "search.searchButton": "検索",
    "search.searching": "検索中...",
    "search.noResults": "結果が見つかりません",
    "search.tryAdjusting": "検索条件を調整してみてください",
    "search.businessesFound": "ビジネスが見つかりました",
    "search.loadingResults": "結果を読み込み中...",
    "search.contactForms": "連絡フォーム",
    "search.contactFormsFound": "連絡フォームが見つかりました",
    "search.contactForm": "連絡フォーム",
    "search.quickSend": "クイック送信",
    "search.viewDetails": "詳細を表示",
    "search.copyFormData": "フォームデータをコピー",
    "search.formDataCopied": "フォームデータがクリップボードにコピーされました",

    // Time formatting
    "time.justNow": "今",
    "time.minuteAgo": "分前",
    "time.minutesAgo": "分前",
    "time.hourAgo": "時間前",
    "time.hoursAgo": "時間前",
    "time.yesterday": "昨日",
    "time.daysAgo": "日前",
    "time.weeksAgo": "週前",
    "time.never": "なし",

    // Admin Dashboard
    "admin.dashboard": "管理者ダッシュボード",
    "admin.users": "ユーザー",
    "admin.actions": "アクション",
    "admin.addUser": "ユーザーを追加",
    "admin.editUser": "ユーザーを編集",
    "admin.deleteUser": "ユーザーを削除",
    "admin.userEmail": "メール",
    "admin.userName": "名前",
    "admin.userPassword": "パスワード",
    "admin.userRole": "役割",
    "admin.userStatus": "ステータス",
    "admin.userCreated": "作成日",
    "admin.userUpdated": "更新日",
    "admin.active": "アクティブ",
    "admin.inactive": "非アクティブ",
    "admin.admin": "管理者",
    "admin.user": "ユーザー",
    "admin.searchUsers": "ユーザーを検索...",
    "admin.noUsers": "ユーザーが見つかりません",
    "admin.loadingUsers": "ユーザーを読み込み中...",
    "admin.confirmDeleteUser": "このユーザーを削除してもよろしいですか？",
    "admin.deleteSuccess": "ユーザーが正常に削除されました",
    "admin.deleteError": "ユーザーの削除中にエラーが発生しました",
    "admin.addSuccess": "ユーザーが正常に追加されました",
    "admin.addError": "ユーザーの追加中にエラーが発生しました",
    "admin.updateSuccess": "ユーザーが正常に更新されました",
    "admin.updateError": "ユーザーの更新中にエラーが発生しました",
    "admin.userActions": "ユーザーアクション",
    "admin.actionType": "アクションタイプ",
    "admin.actionDetails": "詳細",
    "admin.actionDate": "日付",
    "admin.actionIP": "IPアドレス",
    "admin.actionUserAgent": "ユーザーエージェント",
    "admin.noActions": "アクションが見つかりません",
    "admin.loadingActions": "アクションを読み込み中...",
    "admin.pagination": "ページ",
    "admin.of": "の",
    "admin.previous": "前へ",
    "admin.next": "次へ",
    "admin.itemsPerPage": "件/ページ",
    "admin.manageUsersAndMonitor":
      "ユーザーを管理し、システムアクティビティを監視",
  },
  ru: {
    // Navigation
    "nav.dashboard": "Панель управления",
    "nav.dashboard.description": "Обзор и аналитика",
    "nav.search": "Поиск",
    "nav.search.description": "Найти предприятия",
    "nav.history": "История",
    "nav.history.description": "Просмотр истории поиска",
    history: "История",
    "nav.manageGroups": "Управление группами",
    "nav.manageGroups.description": "Управление группами контактов",
    "nav.settings": "Настройки",
    "nav.settings.description": "Настройте свой опыт",
    "nav.testSearch": "Тестовый поиск",
    "nav.testSearch.description": "Тестирование функции поиска",
    "nav.singleWebsite": "Один веб-сайт",
    "nav.singleWebsite.description": "Поиск одного веб-сайта",
    "nav.testMessage": "Тестовое сообщение",
    "nav.testMessage.description": "Тестирование отправки одного сообщения",
    "nav.adminPanel": "Панель администратора",
    "nav.adminPanel.description": "Панель администратора",
    "nav.moreTools": "Дополнительные инструменты",
    "nav.moreTools.description": "Дополнительные функции",
    "nav.archiveSearch": "Архивный поиск",
    "nav.archiveSearch.description": "Поиск в архиве данных",
    "nav.businessOutreach": "Платформа бизнес-аутрич",
    "nav.captchaStatus": "Статус CAPTCHA",

    // Settings page
    "settings.title": "Настройки",
    "settings.description":
      "Настройте свой опыт работы с Auto Reach Pro с помощью персонализированных настроек и предпочтений.",
    "settings.appearance": "Внешний вид",
    "settings.appearance.description":
      "Выберите предпочтительную цветовую схему и тему.",
    "settings.notifications": "Уведомления",
    "settings.notifications.description":
      "Управляйте тем, какие уведомления вы получаете и как.",
    "settings.designSystem": "Система дизайна",
    "settings.designSystem.description":
      "Изучите доступные компоненты пользовательского интерфейса и их варианты.",
    "settings.colorPalette": "Цветовая палитра",
    "settings.colorPalette.description":
      "Доступная цветовая система, используемая во всем интерфейсе.",
    "settings.theme": "Тема",
    "settings.current": "Текущая",
    "settings.light": "Светлая",
    "settings.dark": "Темная",
    "settings.system": "Системная",
    "settings.light.description": "Чистый и яркий интерфейс",
    "settings.dark.description": "Бережно для глаз",
    "settings.system.description": "Следует настройкам ОС",
    "settings.emailNotifications": "Email уведомления",
    "settings.pushNotifications": "Push уведомления",
    "settings.smsNotifications": "SMS уведомления",
    "settings.notificationDescription":
      "Получайте {type} уведомления для важных обновлений",
    "settings.buttonVariants": "Варианты кнопок",
    "settings.buttonSizes": "Размеры кнопок",
    "settings.buttonStates": "Состояния кнопок",
    "settings.cardVariants": "Варианты карточек",
    "settings.tooltipPositions": "Позиции подсказок",
    "settings.resetDefaults": "Сбросить по умолчанию",
    "settings.saveChanges": "Сохранить изменения",
    "settings.primary": "Основной",
    "settings.secondary": "Вторичный",
    "settings.outline": "Контур",
    "settings.ghost": "Призрачный",
    "settings.success": "Успех",
    "settings.warning": "Предупреждение",
    "settings.error": "Ошибка",
    "settings.defaultCard": "Карточка по умолчанию",
    "settings.elevatedCard": "Приподнятая карточка",
    "settings.outlinedCard": "Карточка с контуром",
    "settings.interactiveCard": "Интерактивная карточка",
    "settings.defaultCard.description": "Стандартная карточка с обычным стилем",
    "settings.elevatedCard.description":
      "Карточка с улучшенными тенями и эффектами наведения",
    "settings.outlinedCard.description": "Карточка с тонким стилем границ",
    "settings.interactiveCard.description":
      "Кликабельная карточка с состояниями наведения",
    "settings.topTooltip": "Эта подсказка появляется сверху",
    "settings.bottomTooltip": "Эта подсказка появляется снизу",
    "settings.leftTooltip": "Эта подсказка появляется слева",
    "settings.rightTooltip": "Эта подсказка появляется справа",
    "settings.language": "Язык",
    "settings.language.description":
      "Выберите предпочтительный язык для интерфейса.",
    "settings.english": "Английский",
    "settings.japanese": "Японский",
    "settings.russian": "Русский",
    "settings.english.description": "Язык по умолчанию",
    "settings.japanese.description": "Японский интерфейс",
    "settings.russian.description": "Русский интерфейс",

    // Common UI
    "ui.signOut": "Выйти",
    "ui.user": "Пользователь",
    "ui.loading": "Загрузка...",
    "ui.error": "Ошибка",
    "ui.success": "Успех",
    "ui.warning": "Предупреждение",
    "ui.info": "Информация",
    "ui.confirm": "Подтвердить",
    "ui.cancel": "Отмена",
    "ui.save": "Сохранить",
    "ui.delete": "Удалить",
    "ui.edit": "Редактировать",
    "ui.add": "Добавить",
    "ui.search": "Поиск",
    "ui.filter": "Фильтр",
    "ui.sort": "Сортировка",
    "ui.refresh": "Обновить",
    "ui.close": "Закрыть",
    "ui.open": "Открыть",
    "ui.next": "Следующий",
    "ui.previous": "Предыдущий",
    "ui.submit": "Отправить",
    "ui.reset": "Сбросить",
    "ui.selectAll": "Выбрать все",
    "ui.deselectAll": "Снять выделение",
    "ui.selected": "выбрано",
    "ui.clear": "Очистить",

    // Page titles and headers
    "pages.searchHistory.title": "История поиска",
    "pages.searchHistory.description":
      "Просмотр и управление предыдущими поисками",
    "pages.searchHistory.loading": "Загрузка истории поиска...",
    "pages.searchHistory.noHistory": "История поиска пуста",
    "pages.searchHistory.noResults": "Результаты не найдены",
    "pages.searchHistory.startFirstSearch":
      "Начните первый поиск, чтобы увидеть историю здесь",
    "pages.searchHistory.tryAdjusting": "Попробуйте изменить условия поиска",

    // Search history specific
    "searchHistory.search":
      "Поиск по категории, ключевым словам или областям...",
    "searchHistory.searchType": "Тип",
    "searchHistory.found": "Найдено",
    "searchHistory.businesses": "предприятий",
    "searchHistory.duration": "Продолжительность",
    "searchHistory.date": "Дата",
    "searchHistory.keywords": "Ключевые слова",
    "searchHistory.areas": "Области",
    "searchHistory.results": "Результаты",
    "searchHistory.totalResults": "всего результатов",
    "searchHistory.noResultsFound": "Результаты не найдены.",
    "searchHistory.cleanupExpired": "Очистить истекшие",
    "searchHistory.cleaning": "Очистка...",

    // Pagination

    // CAPTCHA Status page
    "pages.captchaStatus.title": "Статус сервиса CAPTCHA",
    "pages.captchaStatus.troubleshooting": "Решение проблем с CAPTCHA",
    "pages.captchaStatus.errorZeroBalance": "❌ ERROR_ZERO_BALANCE",
    "pages.captchaStatus.errorZeroBalanceDesc":
      "На вашем аккаунте сервиса решения CAPTCHA недостаточно средств. Пополните аккаунт, чтобы продолжить использование автоматического решения CAPTCHA.",
    "pages.captchaStatus.noServiceConfigured": "⚠️ Сервис CAPTCHA не настроен",
    "pages.captchaStatus.noServiceConfiguredDesc":
      "Сервис решения CAPTCHA не настроен. Добавьте ваши API ключи в переменные окружения.",
    "pages.captchaStatus.alternativeSolutions": "💡 Альтернативные решения",
    "pages.captchaStatus.alternativeSolutionsDesc":
      "Используйте несколько сервисов CAPTCHA для надежности",
    "pages.captchaStatus.manualSolving":
      "Реализуйте ручное решение CAPTCHA для критических форм",
    "pages.captchaStatus.captchaFree":
      "Используйте отправку форм без CAPTCHA, когда это возможно",
    "pages.captchaStatus.monitorBalances":
      "Регулярно отслеживайте балансы сервисов",
    "pages.captchaStatus.quickSetupGuide": "Быстрое руководство по настройке",
    "pages.captchaStatus.twoCaptcha": "1. 2captcha.com (Рекомендуется)",
    "pages.captchaStatus.visit2captcha": "Посетить",
    "pages.captchaStatus.createAccount": "Создать аккаунт",
    "pages.captchaStatus.addFunds": "Пополнить счет (минимум $3-5)",
    "pages.captchaStatus.getApiKey": "Получить API ключ",
    "pages.captchaStatus.addToEnv": "Добавить в .env.local:",
    "pages.captchaStatus.antiCaptcha": "2. Anti-Captcha (Альтернатива)",

    // Group management
    "groups.addToGroup": "Добавить в группу",
    "groups.manageGroups": "Управление группами",
    "groups.loadingGroups": "Загрузка групп...",
    "groups.noGroupsFound": "Группы не найдены. Сначала создайте группу.",
    "groups.createFirstGroup": "Создать первую группу",
    "groups.addingToGroup": "Добавление в группу",
    "groups.successfullyAdded": "успешно!",
    "groups.addSelectedToGroup": "Добавить выбранные в группу",
    "groups.selectGroupToAdd": "Выберите группу для добавления",
    "groups.selectedBusinesses": "выбранных предприятий",
    "groups.to": "в:",
    "groups.pleaseSignIn":
      "Пожалуйста, войдите в систему для управления группами.",
    "groups.groupManagement": "Управление группами",
    "groups.visitDedicatedPage":
      "Для управления контактными группами посетите специальную страницу управления группами.",
    "groups.goToGroupManagement": "Перейти к управлению группами",
    "groups.createGroup": "Создать группу",
    "groups.deleteGroup": "Удалить группу",
    "groups.sendMessage": "Отправить сообщение",
    "groups.loading": "Загрузка...",
    "groups.loadingSession": "Загрузка сессии...",
    "groups.loadingMessageForm": "Загрузка...",
    "groups.sending": "Отправка...",
    "groups.messageDeleted": "Сообщение успешно удалено!",
    "groups.messageDeleteError": "Не удалось удалить сообщение",
    "groups.groupCreated": "Группа успешно создана!",
    "groups.groupCreateError": "Не удалось создать группу",
    "groups.groupDeleted": "Группа успешно удалена!",
    "groups.groupDeleteError": "Не удалось удалить группу",
    "groups.contactRemoved": "Контакт успешно удален!",
    "groups.contactRemoveError": "Не удалось удалить контакт",
    "groups.notesUpdated": "Заметки успешно обновлены!",
    "groups.notesUpdateError": "Не удалось обновить заметки",
    "groups.messagingEnabled": "Обмен сообщениями включен",
    "groups.messagingDisabled": "Обмен сообщениями отключен",
    "groups.backgroundSend": "Фоновая отправка",
    "groups.manualSend": "Ручная отправка",
    "groups.retry": "Повторить",
    "groups.manual": "Ручной",
    "groups.notes": "Заметки",
    "groups.addNotes": "Добавить заметки",
    "groups.editNotes": "Редактировать заметки",
    "groups.noNotes": "Заметки еще не добавлены",
    "groups.save": "Сохранить",
    "groups.cancel": "Отмена",
    "groups.edit": "Редактировать",
    "groups.remove": "Удалить",
    "groups.close": "Закрыть",
    "groups.contacts": "контактов",
    "groups.created": "Создано",
    "groups.noContacts": "Контактов пока нет",
    "groups.noContactsFiltered": "Контакты не найдены",
    "groups.addContactsFromSearch":
      "Добавьте контакты в эту группу из результатов поиска.",
    "groups.noContactsWithStatus": "Контакты со статусом {status} не найдены.",
    "groups.filterByStatus": "Фильтр по статусу:",
    "groups.all": "Все",
    "groups.success": "Успех",
    "groups.failed": "Неудача",
    "groups.pending": "В ожидании",
    "groups.messageContext": "Контекст сообщения для",
    "groups.customizeMessage": "Настроить сообщение",
    "groups.subject": "Тема",
    "groups.message": "Сообщение",
    "groups.customSubject": "Пользовательская тема (необязательно)",
    "groups.customMessage": "Пользовательское сообщение (необязательно)",
    "groups.backgroundMessageStatus": "Статус фонового сообщения",
    "groups.individualBackgroundSend":
      "Отправить сообщение этому контакту, используя фоновую автоматизацию",
    "groups.retryOpenForm": "Повторить - Открыть контактную форму в новом окне",
    "groups.markAsManuallySent": "Отметить как отправленное вручную",
    "groups.removeFromGroup": "Удалить из группы",
    "groups.lastSent": "Последняя отправка",
    "groups.lastFailed": "Последняя неудача",
    "groups.retryFailedContacts": "Повторить неудачные контакты",
    "groups.someContactsFailed":
      "Некоторые контакты не смогли получить сообщения. Вы можете повторить их индивидуально:",
    "groups.retryThisContact":
      "Повторить этот контакт - Открыть форму в новом окне",
    "groups.savedMessages": "Сохраненные сообщения для",
    "groups.noSavedMessages":
      "Сохраненных сообщений пока нет. Сохраните сообщение, чтобы увидеть его здесь.",
    "groups.use": "Использовать",
    "groups.messageRecipients": "Получатели сообщений",
    "groups.onlyEnabledContacts":
      "Только контакты с включенным обменом сообщениями получат это сообщение",
    "groups.backgroundSendTitle":
      "Отправить сообщения в фоне, используя автоматизацию браузера",
    "groups.manualSendTitle": "Отправить сообщения немедленно",
    "groups.autoGenerateSubject":
      "Оставьте пустым для автоматической генерации темы из названий предприятий",
    "groups.enterMessageSubject": "Введите тему сообщения",
    "groups.enterMessageBody": "Введите ваше сообщение",
    "groups.aiSuggestions":
      "Получить предложения ИИ для улучшения вашего сообщения",
    "groups.aiImprovedMessage": "ИИ улучшил ваше сообщение!",
    "groups.aiCorrectionFailed": "Исправление ИИ не удалось",
    "groups.clickAiButton":
      "Нажмите кнопку ИИ, чтобы получить предложения по улучшению сообщения",
    "groups.groupInformation": "Информация о группе",
    "groups.of": "из",
    "groups.enabled": "включено",
    "groups.confirmDeleteGroup":
      "Вы уверены, что хотите удалить эту группу? Это действие нельзя отменить.",
    "groups.confirmRemoveContact":
      "Вы уверены, что хотите удалить этот контакт из группы?",
    "groups.testSendMessage": "Тестовая отправка сообщения",
    "groups.groupDetailsClosed": "Детали группы закрыты",
    "groups.messagingToggleError":
      "Не удалось обновить переключатель обмена сообщениями",
    "groups.messagingEnabledFor": "Обмен сообщениями включен для",
    "groups.messagingDisabledFor": "Обмен сообщениями отключен для",
    "groups.queuedMessageFor":
      "Сообщение для {businessName} поставлено в очередь для фоновой обработки.",
    "groups.failedToQueueMessage":
      "Не удалось поставить в очередь сообщение для {businessName}",
    "groups.queuedMessages":
      "{count} сообщений поставлено в очередь для фоновой обработки. Проверьте панель прогресса ниже.",
    "groups.noContactsEnabled":
      "Нет контактов с включенным обменом сообщениями. Пожалуйста, включите обмен сообщениями хотя бы для одного контакта.",
    "groups.messagesSentSuccessfully":
      "Сообщения успешно отправлены всем {count} контактам!",
    "groups.messagesFailed":
      "{count} сообщений не удалось отправить: {businessNames}",
    "groups.failedToSendTo": "Не удалось отправить {businessName}: {error}",
    "groups.markedAsManuallySent":
      "Отмечено как отправленное вручную для {businessName}",
    "groups.failedToUpdateStatus": "Не удалось обновить статус",
    "groups.formOpenedAndFilled":
      "Форма открыта и заполнена для {businessName}. Пожалуйста, проверьте и отправьте вручную.",
    "groups.formOpened":
      "Форма открыта для {businessName}. Пожалуйста, заполните вручную.",
    "groups.noContactPage":
      "Для этого предприятия нет доступной контактной страницы или веб-сайта",
    "groups.popupBlocked":
      "Всплывающее окно заблокировано! Пожалуйста, разрешите всплывающие окна для этого сайта.",
    "groups.businessMessageContextSaved": "Контекст бизнес-сообщения сохранен!",
    "groups.failedToSaveContext":
      "Не удалось сохранить контекст бизнес-сообщения",
    "groups.description": "Описание",
    "groups.color": "Цвет",
    "groups.enterGroupName": "Введите название группы",
    "groups.enterGroupDescription": "Введите описание группы (необязательно)",

    // Map page
    "map.title": "Интерактивная карта",
    "map.markers": "маркеров",
    "map.instructions": "Как использовать:",
    "map.clickInstruction":
      "Нажмите в любое место на карте, чтобы добавить маркер и получить координаты",
    "map.selectInstruction":
      "Выберите маркеры из списка ниже для просмотра деталей",
    "map.copyInstruction":
      "Нажмите на значения координат, чтобы скопировать их в буфер обмена",
    "map.selectedLocation": "Выбранное место",
    "map.latitude": "Широта:",
    "map.longitude": "Долгота:",
    "map.timestamp": "Время:",
    "map.clickToCopy": "Нажмите, чтобы скопировать",
    "map.copyCoordinates": "Копировать координаты",
    "map.coordinateHistory": "История координат",
    "map.noCoordinates":
      "Пока нет координат. Нажмите на карту, чтобы добавить!",
    "map.deleteMarker": "Удалить маркер",
    "map.clearAll": "Очистить все",
    "map.geographicalSearch": "Географический поиск",
    "map.searchRadius": "Радиус поиска",
    "map.searchNearby": "Поиск рядом",
    "map.searching": "Поиск...",
    "map.clear": "Очистить",
    "map.selectLocationFirst": "Сначала выберите место на карте",
    "map.searchError": "Произошла ошибка при поиске",
    "map.searchResults": "Результаты поиска",
    "map.viewOnMap": "Показать на карте",
    "map.quickActions": "Быстрые действия",
    "map.defaultLocation": "Местоположение по умолчанию",
    "map.searchFromDefault": "🔍 Поиск из местоположения по умолчанию",
    "map.resetToDefault": "🏠 Сбросить к виду по умолчанию",
    "map.quickSearch":
      "Используйте 'Поиск из местоположения по умолчанию' для быстрого поиска бизнеса в центральном Токио",
    "map.contactClick":
      "Нажмите кнопки контактов, чтобы скопировать номера телефонов, электронную почту или посетить веб-сайты",
    "map.locationSearch": "Поиск места",
    "map.searchPlaceholder": "Введите место (например, Шибуя, Гинза, Асакуса)",
    "map.enterLocation": "Пожалуйста, введите место",
    "map.locationNotFound":
      "Место не найдено. Попробуйте другой поисковый запрос.",
    "map.locationSearchInstruction":
      "Используйте поиск места, чтобы найти конкретные места в Токио",

    // Settings - Company & Product Management
    "settings.company": "Информация о компании",
    "settings.company.description": "Управление деталями и описанием компании",
    "settings.companyDescription": "Описание компании",
    "settings.companyDescription.placeholder":
      "Опишите вашу компанию, услуги и что вас отличает...",
    "settings.companyDescriptionRequired": "Описание компании обязательно",
    "settings.saveCompany": "Сохранить информацию о компании",
    "settings.savingCompany": "Сохранение...",
    "settings.companySaved": "Информация о компании успешно сохранена!",
    "settings.companySaveError": "Не удалось сохранить информацию о компании",
    "settings.companyLoadError": "Не удалось загрузить информацию о компании",

    "settings.products": "Управление продуктами",
    "settings.products.description":
      "Создание и управление каталогом продуктов",
    "settings.addProduct": "Добавить новый продукт",
    "settings.productDescription": "Описание продукта",
    "settings.productDescription.placeholder": "Подробное описание продукта...",
    "settings.productDescriptionRequired": "Описание продукта обязательно",
    "settings.saveProduct": "Добавить продукт",
    "settings.savingProduct": "Сохранение...",
    "settings.productSaved": "Продукт успешно добавлен!",
    "settings.productSaveError": "Не удалось добавить продукт",
    "settings.yourProducts": "Ваши продукты",
    "settings.editProduct": "Редактировать",
    "settings.deleteProduct": "Удалить",
    "settings.productUpdated": "Продукт успешно обновлен!",
    "settings.productUpdateError": "Не удалось обновить продукт",
    "settings.productDeleted": "Продукт успешно удален!",
    "settings.productDeleteError": "Не удалось удалить продукт",
    "settings.productsLoadError": "Не удалось загрузить продукты",
    "settings.noProducts": "Продукты не найдены",
    "settings.noProducts.description":
      "Начните с добавления вашего первого продукта",
    "settings.created": "Создано",
    "settings.loading": "Загрузка...",
    "settings.charactersRemaining": "символов осталось",
    "settings.authRequired":
      "Пожалуйста, войдите в систему для доступа к настройкам",
    "settings.authError": "Ошибка аутентификации. Пожалуйста, войдите снова.",
    "settings.databaseSetupRequired":
      "База данных не настроена. Пожалуйста, запустите скрипт настройки в Supabase SQL Editor.",

    // Search functionality
    "search.addToGroup": "Добавить в группу",
    "search.addToGroupTitle": "Добавить в группу",
    "search.addingToGroup": "Добавление в группу",
    "search.successfullyAdded": "успешно!",
    "search.loadingGroups": "Загрузка групп...",
    "search.noGroupsFound": "Группы не найдены. Сначала создайте группу.",
    "search.createFirstGroup": "Создать первую группу",
    "search.manageGroups": "Управление группами",
    "search.visitDedicatedPage":
      "Для управления контактными группами посетите специальную страницу управления группами.",
    "search.goToGroupManagement": "Перейти к управлению группами",
    "search.selectGroupToAdd": "Выберите группу для добавления",
    "search.selectedBusinesses": "выбранных предприятий",
    "search.to": "в:",
    "search.pleaseSignIn":
      "Пожалуйста, войдите в систему для управления группами.",
    "search.groupManagement": "Управление группами",
    "search.searchBusinesses": "Поиск предприятий",
    "search.searchDescription":
      "Найдите предприятия по категории, региону или ключевым словам",
    "search.selectCategory": "Выберите категорию",
    "search.selectRegion": "Выберите регион",
    "search.enterKeywords": "Введите ключевые слова",
    "search.searchButton": "Поиск",
    "search.searching": "Поиск...",
    "search.noResults": "Результаты не найдены",
    "search.tryAdjusting": "Попробуйте изменить критерии поиска",
    "search.businessesFound": "предприятий найдено",
    "search.loadingResults": "Загрузка результатов...",
    "search.contactForms": "Контактные формы",
    "search.contactFormsFound": "контактных форм найдено",
    "search.contactForm": "Контактная форма",
    "search.quickSend": "Быстрая отправка",
    "search.viewDetails": "Просмотр деталей",
    "search.copyFormData": "Копировать данные формы",
    "search.formDataCopied": "Данные формы скопированы в буфер обмена",

    // Form and actions
    "actions.selectAll": "Выбрать все",
    "actions.clearSelection": "Очистить выбор",
    "actions.selected": "выбрано",
    "actions.of": "из",
    "actions.previous": "Предыдущий",
    "actions.next": "Следующий",
    "actions.page": "Страница",
    "actions.cancel": "Отмена",
    "actions.website": "Веб-сайт",
    "actions.enterWebsite": "Пожалуйста, введите URL веб-сайта",
    "actions.search": "Поиск",
    "actions.searching": "Поиск...",
    "actions.copyFormData": "Копировать данные формы для ручной отправки",
    "actions.manualSubmissionNote":
      "Система попытается автоматически найти и отправить данные в контактные формы. Вы также можете скопировать данные формы и отправить их вручную в любую найденную контактную форму.",

    // Authentication
    "auth.welcomeBack": "Добро пожаловать",
    "auth.signInToAccount": "Войдите в свой аккаунт AutoReachPro",
    "auth.emailAddress": "Адрес электронной почты",
    "auth.password": "Пароль",
    "auth.signIn": "Войти",
    "auth.invalidCredentials": "Неверный email или пароль",
    "auth.errorOccurred": "Произошла ошибка. Пожалуйста, попробуйте еще раз.",
    "auth.loading": "Загрузка...",

    // Business and contact
    "business.name": "Имя",
    "business.email": "Email",
    "business.phone": "Телефон",
    "business.company": "Компания",
    "business.subject": "Тема",
    "business.message": "Сообщение",
    "business.address": "Адрес",
    "business.website": "Веб-сайт",
    "business.contact": "Контакты",
    "business.contactPage": "Контактная страница",
    "business.rating": "Рейтинг",
    "business.reviews": "Отзывы",
    "business.category": "Категория",
    "business.region": "Регион",
    "business.area": "Область",
    "business.station": "Станция",
    "business.status": "Статус",
    "business.lastSearched": "Последний поиск",

    // Additional auth and common text
    "auth.dontHaveAccount": "Нет аккаунта?",
    "auth.createOneNow": "Создайте сейчас",
    "auth.agreeToTerms": "Входя в систему, вы соглашаетесь с нашими",
    "auth.termsOfService": "Условиями использования",
    "auth.and": "и",
    "auth.privacyPolicy": "Политикой конфиденциальности",
    "auth.enterEmail": "Введите ваш email",
    "auth.enterPassword": "Введите ваш пароль",
    "auth.signingIn": "Вход в систему...",

    // Dashboard
    "dashboard.welcomeBack": "Добро пожаловать",
    "dashboard.welcomeMessage":
      "Вот что происходит с вашими кампаниями по привлечению бизнеса",
    "dashboard.totalSearches": "Всего поисков",
    "dashboard.businessesFound": "Найдено предприятий",
    "dashboard.contactForms": "Контактные формы",
    "dashboard.successRate": "Процент успеха",
    "dashboard.fromLastMonth": "по сравнению с прошлым месяцем",
    "dashboard.quickActions": "Быстрые действия",
    "dashboard.startSearch": "Начать поиск",
    "dashboard.startSearchDesc": "Найти новые предприятия",
    "dashboard.manageGroups": "Управление группами",
    "dashboard.manageGroupsDesc": "Организовать контакты",
    "dashboard.testMessage": "Тестовое сообщение",
    "dashboard.testMessageDesc": "Отправить тестовые письма",
    "dashboard.viewHistory": "Просмотр истории",
    "dashboard.viewHistoryDesc": "Прошлые поиски",
    "dashboard.recentSearches": "Недавние поиски",
    "dashboard.viewAll": "Просмотреть все",
    "dashboard.noRecentSearches": "Нет недавних поисков",
    "dashboard.startFirstSearch": "Начните свой первый поиск",
    "dashboard.found": "найдено",
    "dashboard.noRegionsSpecified": "Регионы не указаны",
    "dashboard.systemAction": "Системное действие",

    // Time formatting
    "time.justNow": "Только что",
    "time.minuteAgo": "минуту назад",
    "time.minutesAgo": "минут назад",
    "time.hourAgo": "час назад",
    "time.hoursAgo": "часов назад",
    "time.yesterday": "Вчера",
    "time.daysAgo": "дней назад",
    "time.weeksAgo": "недель назад",
    "time.never": "Никогда",

    // Admin Dashboard
    "admin.dashboard": "Панель администратора",
    "admin.users": "Пользователи",
    "admin.actions": "Действия",
    "admin.addUser": "Добавить пользователя",
    "admin.editUser": "Редактировать пользователя",
    "admin.deleteUser": "Удалить пользователя",
    "admin.userEmail": "Email",
    "admin.userName": "Имя",
    "admin.userPassword": "Пароль",
    "admin.userRole": "Роль",
    "admin.userStatus": "Статус",
    "admin.userCreated": "Создан",
    "admin.userUpdated": "Обновлен",
    "admin.active": "Активный",
    "admin.inactive": "Неактивный",
    "admin.admin": "Администратор",
    "admin.user": "Пользователь",
    "admin.searchUsers": "Поиск пользователей...",
    "admin.noUsers": "Пользователи не найдены",
    "admin.loadingUsers": "Загрузка пользователей...",
    "admin.confirmDeleteUser":
      "Вы уверены, что хотите удалить этого пользователя?",
    "admin.deleteSuccess": "Пользователь успешно удален",
    "admin.deleteError": "Ошибка при удалении пользователя",
    "admin.addSuccess": "Пользователь успешно добавлен",
    "admin.addError": "Ошибка при добавлении пользователя",
    "admin.updateSuccess": "Пользователь успешно обновлен",
    "admin.updateError": "Ошибка при обновлении пользователя",
    "admin.userActions": "Действия пользователей",
    "admin.actionType": "Тип действия",
    "admin.actionDetails": "Детали",
    "admin.actionDate": "Дата",
    "admin.actionIP": "IP адрес",
    "admin.actionUserAgent": "Пользовательский агент",
    "admin.noActions": "Действия не найдены",
    "admin.loadingActions": "Загрузка действий...",
    "admin.pagination": "Страница",
    "admin.of": "из",
    "admin.previous": "Предыдущая",
    "admin.next": "Следующая",
    "admin.itemsPerPage": "элементов на странице",
    "admin.manageUsersAndMonitor":
      "Управление пользователями и мониторинг системной активности",
  },
};

interface LanguageProviderProps {
  children: React.ReactNode;
  defaultLanguage?: Language;
  storageKey?: string;
}

export function LanguageProvider({
  children,
  defaultLanguage = "ja",
  storageKey = "autoreach-language",
}: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(defaultLanguage);

  useEffect(() => {
    const savedLanguage = localStorage.getItem(storageKey) as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, [storageKey]);

  useEffect(() => {
    localStorage.setItem(storageKey, language);
  }, [language, storageKey]);

  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language]?.[key];
    if (!translation) {
      console.warn(
        `Translation missing for key: ${key} in language: ${language}`
      );
      translation = translations.en[key] || key;
    }

    // Replace parameters in the translation
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        translation = translation.replace(`{${param}}`, value);
      });
    }

    return translation;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}
